ALL:
  HEALTH_MAX:
    ICON: ""
    COLOR: "ยงc"
  HEALTH:
    ICON: "โค"
    COLOR: "ยงc"
  HEALTH_REGEN:
    ICON: ""
    COLOR: "ยงc"
  ATTACK:
    ICON: "๐ก"
    COLOR: "ยง6"
  ATTACK_MULTIPLIER:
    ICON: "๐ก"
    COLOR: "ยง6"
  POWER:
    ICON: "๐ก"
    COLOR: "ยงd"
  POWER_MULTIPLIER:
    ICON: "๐ก"
    COLOR: "ยงd"
  DEFENCE:
    ICON: "๐ก"
    COLOR: "ยง6"
  MR:
    ICON: "๐ก"
    COLOR: "ยงd"
  RANGE:
    ICON: "โ"
    COLOR: "ยงf"
  RADIUS:
    ICON: ""
    COLOR: "ยงd"
  TARGET:
    ICON: "โ"
    COLOR: "ยงb"
  COOLDOWN:
    ICON: "โ"
    COLOR: "ยง7"
  COOLDOWN_REDUCTION:
    ICON: "โ"
    COLOR: "ยงd"
  MANA:
    ICON: "โ"
    COLOR: "ยงb"
  MANA_MAX:
    ICON: "โ"
    COLOR: "ยงb"
  MANA_REGEN:
    ICON: "โ"
    COLOR: "ยงb"
  MANA_COST:
    ICON: "โ"
    COLOR: "ยง3"
  MANA_REGEN:
    ICON: "โ"
    COLOR: "ยงb"
  DURATION:
    ICON: ""
    COLOR: "ยง9"
  PROJECTILE_SPEED:
    ICON: ""
    COLOR: "ยงc"
  PROJECTILE_AMOUNT:
    ICON: ""
    COLOR: "ยงc"
  EFFECT_DURATION:
    ICON: ""
    COLOR: "ยงc"
  EFFECT_FREQUENCY:
    ICON: ""
    COLOR: "ยงc"


PLAYER:
  - "HEALTH"
  - "HEALTH_MAX"
  - "MANA"
  - "MANA_MAX"
  - "MANA_REGEN"
  - "ATTACK"
  - "POWER"
  - "DEFENCE"
  - "MR"

WEAPON:
  - "COOLDOWN"
  - "ATTACK"
  - "ATTACK_MULTIPLIER"
  - "POWER"
  - "POWER_MULTIPLIER"
  - "MANA"
  - "RADIUS"
  - "RANGE"
  - PROJECTILE_SPEED
  - PROJECTILE_AMOUNT

SKILL:
  - "ATTACK"
  - "ATTACK_MULTIPLIER"
  - "POWER"
  - "POWER_MULTIPLIER"
  - "RADIUS"
  - "RANGE"
  - "MANA"
  - "COOLDOWN"
  - "DURATION"
  - PROJECTILE_SPEED
  - PROJECTILE_AMOUNT

GIFT:
  - "ATTACK"
  - "POWER"
  - "MANA"
  - "MANA_REGEN"
  - "HEALTH"
  - "HEALTH_REGEN"
  - "DEFENCE"
  - "MR"
  - "COOLDOWN"
  - "RANGE"
  - "RADIUS"
  - "PROJECTILE"
  - PROJECTILE_SPEED
  - PROJECTILE_AMOUNT

MOB:
  - "HEALTH"
  - "DEFENCE"
  - "MR"
  - "ATTACK"
  - "POWER"
  - "SPEED"

NPC:
  - "HEALTH"
  - "DEFENCE"
  - "MR"
  - "ATTACK"
  - "POWER"
  - "SPEED"