ALL:
  HEALTH_MAX:
    ICON: ""
    COLOR: "ยงc"
  HEALTH:
    ICON: "โค"
    COLOR: "ยงc"
  HEALTH_REGEN:
    ICON: ""
    COLOR: "ยงc"
  ATTACK:
    ICON: "๐ก"
    COLOR: "ยง6"
  ATTACK_MULTIPLIER:
    ICON: "๐ก"
    COLOR: "ยง6"
  DEFENCE:
    ICON: "๐ก"
    COLOR: "ยง6"
  DEFENCE_REDUCTION:
    ICON: ""
    ICON_END: "%"
    COLOR: "ยงc"
  DEFENCE_REDUCTION_FACING:
    ICON: ""
    ICON_END: "%"
    COLOR: "ยงc"
  RANGE:
    ICON: "โ"
    COLOR: "ยงf"
  RADIUS:
    ICON: ""
    COLOR: "ยงd"
  COOLDOWN:
    ICON: "โ"
    COLOR: "ยง7"
  COOLDOWN_REDUCTION:
    ICON: "โ"
    COLOR: "ยงd"
  PROJECTILE_SPEED:
    ICON: ""
    COLOR: "ยงc"
  PROJECTILE_AMOUNT:
    ICON: ""
    COLOR: "ยงc"
  EFFECT_DURATION:
    ICON: ""
    COLOR: "ยงc"
  EFFECT_FREQUENCY:
    ICON: ""
    COLOR: "ยงc"
  CHARITY:
    ICON: ""
    COLOR: "ยงc"
  USAGE_ADDITIONAL:
    ICON: ""
    COLOR: "ยงc"
  KNOCKBACK:
    ICON: ""
    COLOR: "ยงc"
  PROPULSION:
    ICON: ""
    COLOR: "ยงc"
  DURABILITY:
    ICON: ""
    COLOR: "ยงc"

MOB:
  - "HEALTH"
  - "DEFENCE"
  - "MR"
  - "ATTACK"
  - "POWER"
  - "SPEED"