ALL:
  HEALTH_MAX:
    ICON: ""
    COLOR: "ยงc"
  HEALTH:
    ICON: "โค"
    COLOR: "ยงc"
  HEALTH_REGEN:
    ICON: ""
    COLOR: "ยงc"
  ATTACK:
    ICON: "๐ก"
    COLOR: "ยง6"
  ATTACK-2:
    ICON: "๐ก"
    COLOR: "ยง6"
  ATTACK_MULTIPLIER:
    ICON: "๐ก"
    COLOR: "ยง6"
  DEFENCE:
    ICON: "๐ก"
    COLOR: "ยง6"
  RANGE:
    ICON: "โ"
    COLOR: "ยงf"
  RADIUS:
    ICON: ""
    COLOR: "ยงd"
  COOLDOWN:
    ICON: "โ"
    COLOR: "ยง7"
  COOLDOWN_REDUCTION:
    ICON: "โ"
    COLOR: "ยงd"
  PROJECTILE_SPEED:
    ICON: ""
    COLOR: "ยงc"
  PROJECTILE_AMOUNT:
    ICON: ""
    COLOR: "ยงc"
  EFFECT_DURATION:
    ICON: ""
    COLOR: "ยงc"
  EFFECT_FREQUENCY:
    ICON: ""
    COLOR: "ยงc"
  EFFECT_ATTACK:
    ICON: ""
    COLOR: "ยงc"
  EFFECT_ATTACK_MULTIPLIER:
    ICON: ""
    COLOR: "ยงc"
  CHARITY:
    ICON: ""
    COLOR: "ยงc"

PLAYER:
  - HEALTH
  - HEALTH_MAX
  - ATTACK
  - DEFENCE
  - CHARITY

WEAPON:
  - COOLDOWN
  - ATTACK
  - ATTACK_MULTIPLIER
  - RADIUS
  - RANGE
  - PROJECTILE_SPEED
  - PROJECTILE_AMOUNT
  - CHARITY

SKILL:
  - ATTACK
  - ATTACK_MULTIPLIER
  - RADIUS
  - RANGE
  - COOLDOWN
  - "DURATION"
  - PROJECTILE_SPEED
  - PROJECTILE_AMOUNT
  - CHARITY

GIFT:
  - "ATTACK"
  - "POWER"
  - "MANA"
  - "MANA_REGEN"
  - "HEALTH"
  - "HEALTH_REGEN"
  - "DEFENCE"
  - "MR"
  - "COOLDOWN"
  - "RANGE"
  - "RADIUS"
  - "PROJECTILE"
  - PROJECTILE_SPEED
  - PROJECTILE_AMOUNT

MOB:
  - "HEALTH"
  - "DEFENCE"
  - "MR"
  - "ATTACK"
  - "POWER"
  - "SPEED"

NPC:
  - "HEALTH"
  - "DEFENCE"
  - "MR"
  - "ATTACK"
  - "POWER"
  - "SPEED"